theme: jekyll-theme-minimal
title: Shuxi's Page for CIT 281
description: A place for projects and labs completed in CIT 281 in Spring 2021
logo: https://raw.githubusercontent.com/shuxi-wu/shuxi-wu.github.io/main/nick-morrison-FHnnjk1Yj7Y-unsplash.jpg
